#!/bin/sh

set -eu

cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $(py3versions -s); do
    $py -m nose2 --verbose --plugin nose2.plugins.doctests --with-doctest \
            --start-dir /usr/share/dh-python/dhpython

    PYTHONPATH=/usr/share/dh-python $py -m nose2 -v tests
done
